name: '${project.name}'
version: '${project.version}'
main: pl.ynfuien.yadmincore.YAdminCore
api-version: '1.20'
softdepend: [ PlaceholderAPI, spark ]
author: Ynfuien
description: '${project.description}'
website: '${project.url}'

commands:
  yadmincore:
    aliases: [yac]
    description: Plugin's main command
    permission: yadmincore.main

  heal:
    description: Heals player
    permission: yadmincore.heal

  feed:
    description: Feeds player
    permission: yadmincore.feed

  item:
    aliases: [i]
    description: Gives an item
    permission: yadmincore.item

  memory:
    aliases: [mem, server]
    description: Shows information about server memory etc.
    permission: yadmincore.memory

  tp:
    description: Teleports player to player or location
    permission: yadmincore.tp

  tphere:
    aliases: [s]
    description: Teleports player to you
    permission: yadmincore.tphere

  tpoffline:
    aliases: [offlinetp]
    description: Teleports to player's logout location
    permission: yadmincore.tpoffline

  back:
    description: Teleports player back to last location
    permission: yadmincore.back

  god:
    aliases: [godmode]
    description: Enables godmode
    permission: yadmincore.god

  gm:
    aliases: [gamemode]
    description: Changes your gamemode
    permission: yadmincore.gamemode

  entity:
    aliases: [entityinfo, player, playerinfo, whois]
    description: Gets info about the entity/player
    permission: yadmincore.entity

  fly:
    description: Toggles fly mode for the player
    permission: yadmincore.fly

  enchant:
    description: Enchants item in the hand
    permission: yadmincore.enchant

  anvil:
    description: Opens an anvil
    permission: yadmincore.anvil

  cartographytable:
    description: Opens a cartography table
    permission: yadmincore.cartographytable

  enderchest:
    aliases: [ec]
    description: Opens player's enderchest
    permission: yadmincore.enderchest

  grindstone:
    description: Opens a grindstone
    permission: yadmincore.grindstone

  loom:
    description: Opens a loom
    permission: yadmincore.loom

  smithingtable:
    description: Opens a smithing table
    permission: yadmincore.smithingtable

  stonecutter:
    description: Opens a stonecutter
    permission: yadmincore.stonecutter

  workbench:
    aliases: [wb, craft]
    description: Opens a workbench
    permission: yadmincore.workbench
